### ISSUE TITLE
Add short KPI output option

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/performance-analysis-tool#3]
For https://github.com/raiden-network/raiden/issues/5956 we want to collect performance measurements to a central location. As a first step, we should have an option to create machine readable aggregated output, that can be posted to a processor, e.g.:
- a stats collection dashboard, that follows performance over time
- a chat channel, e.g. `#monitoring`

**Comment by Dominik1999** [comment]
nice, more repos!

**Comment by konradkonrad** [comment]
see also https://github.com/raiden-network/raiden/issues/5901

**Comment by konradkonrad** [comment]
ToDo:
--------

- implement filtering the reported tasks i.e. ```["Transfer*", "*ChannelTask", "DepositTask", "*MS*", "*PFS*"]```
- implement `post_to_chat`
- deploy as docker image to scenario player servers
- add to scenario player playbook
