### ISSUE TITLE
PlotlyError: Your list is empty.

### ISSUE THREAD

**Issue by karlb** [raiden-network/performance-analysis-tool#7]
The following error stopped the nightly SP run (nightly-20210107T215431.log) on SP1.
```
Traceback (most recent call last):^M
  File "/performance-analysis/analysis.py", line 329, in <module>^M
    main()^M
  File "/performance-analysis/analysis.py", line 317, in main^M
    draw_gantt(output_directory, filled_rows, summary)^M
  File "/performance-analysis/analysis.py", line 128, in draw_gantt^M
    width=1680,^M
  File "/usr/local/lib/python3.7/site-packages/plotly/figure_factory/_gantt.py", line 729, in create_gantt^M
    chart = validate_gantt(df)^M
  File "/usr/local/lib/python3.7/site-packages/plotly/figure_factory/_gantt.py", line 46, in validate_gantt^M
    raise exceptions.PlotlyError("Your list is empty. It must contain "^M
_plotly_utils.exceptions.PlotlyError: Your list is empty. It must contain at least one dictionary.^M
```

**Comment by ezdac** [comment]
This will happen when the content list is empty,
possibly due to `read_raw_content` returning an empty list:
https://github.com/raiden-network/performance-analysis-tool/blob/c71364190c7fb69fede501dfd9c1ed4177b10b7f/analysis.py#L306

**Comment by ezdac** [comment]
The log that is analysed by the performance tool does neither contain the expected output that specifies the run_number, e.g. 
```
{"run_number": 4579, "event": "Run number", "logger": "scenario_player.runner", "level": "info", "timestamp": "2021-01-07 23:20:42.320901"}
```
nor does it contain a successful task that shows task runtime information, e.g.:

```
{
  "id": "4",
  "task": "<OpenChannelTask: {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000}>",
  "runtime": 183.0317045627162,
  "event": "Task successful",
  "logger": "scenario_player.tasks.base",
  "level": "info",
  "timestamp": "2021-01-07 23:25:42.140064"
}
```

This is the parsing logic:

https://github.com/raiden-network/performance-analysis-tool/blob/c71364190c7fb69fede501dfd9c1ed4177b10b7f/analysis.py#L103-L110

First of all we should either produces NO output if no data for e.g. a gantt chart is available in the logs,
or show a more informed error message.
Both would come down to something like:

```python
if not stripped_content or not run_number:
    # don't run draw_gantt( )
    # or
    raise Exception("Scenario didn't produce analysable log output")
    
```

Also, shouldn't the scenario-player always log the run-number, and shouldn't all tasks (wether successful or not) show their `run_time`?
